### ISSUE TITLE
Error on windows: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by M-Kristof** [python-adaptive/adaptive#225] opened 2019-10-18 14:41 UTC
I am encountering a problem when running lists of learners in a jupyterlab notebook on a windows machine.

For example, when trying out 'Balancing learner' of the introductory notebook,
```python
import adaptive
adaptive.notebook_extension()

# Import modules that are used in multiple cells
import holoviews as hv
import numpy as np
from functools import partial
import random

def h(x, offset=0):
    a = 0.01
    return x + a**2 / (a**2 + (x - offset)**2)

learners = [adaptive.Learner1D(partial(h, offset=random.uniform(-1, 1)),
            bounds=(-1, 1)) for i in range(10)]

bal_learner = adaptive.BalancingLearner(learners)
runner = adaptive.Runner(bal_learner, goal=lambda l: l.loss() < 0.01)
runner.live_info()
```

I get the following error message:
```Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at C:\ProgramData\Anaconda3\lib\asyncio\tasks.py:596> exception=AssertionError('daemonic processes are not allowed to have children')>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\nanny.py", line 245, in start
    response = await self.instantiate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\nanny.py", line 328, in instantiate
    result = await self.process.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\nanny.py", line 502, in start
    await self.process.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\process.py", line 33, in _call_and_set_future
    res = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\process.py", line 190, in _start
    process.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 110, in start
    'daemonic processes are not allowed to have children'
```

It works fine on linux.

**Comment by akhmerov** [comment] 2019-10-18 15:06
Seems to be a general limitation of multiprocessing on windows: https://stackoverflow.com/questions/6974695/python-process-pool-non-daemonic

**Comment by basnijholt** [comment] 2019-10-18 15:09
This shouldn't happen because Windows *should* use `distributed` instead of `multiprocessing`:

https://github.com/python-adaptive/adaptive/blob/5db0f7376e20af666c7e64b3fa13b333fe946445/adaptive/runner.py#L43-L60

Can you check if `os.name == "nt"` and `adaptive.runner. _default_executor`?

**Comment by M-Kristof** [comment] 2019-10-21 08:15
The answer is yes to both. It is using `distributed`.

**Comment by jbweston** [comment] 2019-11-21 10:43
This may well be a bug in `distributed`; further investigation needed.

**Comment by jbweston** [comment] 2019-11-21 10:45
possibly related: https://github.com/dask/distributed/issues/2142 https://github.com/dask/distributed/issues/2718

**Comment by basnijholt** [comment] 2019-12-17 21:37
We were able to reproduce this in https://github.com/python-adaptive/adaptive/pull/247 where we added tests for Windows.

It seems like you should just be able to use a `ProcessPoolExecutor`. When that PR is merged, it will become the default.

**Comment by jbweston** [comment] 2020-04-28 19:27
@M-Kristof, seems that #247 was merged and tests are passing on Windows.

I'll close this issue and you can re-open it if the problem resurfaces.

**Closed by jbweston** 2020-04-28 19:27 UTC
Labels: Runner, bug
