### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by rahimentezari** [python-adaptive/adaptive#296] opened 2020-12-01 07:17 UTC
Is it possible to use GPU for speedup? I need to use adaptive.learner.triangulation

**Comment by akhmerov** [comment] 2020-12-01 17:12
I don't think triangulation would benefit from GPU—it does random access on small chunks of data with a lot of reads and writes.

It would benefit from rewriting in a compiled language (or maybe using e.g. numba for jit): right now it's all Python code.

**Comment by jonas-eschle** [comment] 2021-08-29 07:22
I agree, GPU on this level does not make sense. In general, vectorization of the problem is rather impossible because of the adaptive nature of the problem.

**Comment by akhmerov** [comment] 2021-08-29 09:48
Closing as no action.

**Closed by akhmerov** 2021-08-29 09:48 UTC
