### ISSUE TITLE
jupyter notebook kernels dead after running "import adaptive"

### ISSUE THREAD

**Issue by mingweii** [python-adaptive/adaptive#298] opened 2021-01-14 16:33 UTC
I just installed adaptive and tried to run "import adaptive" on the jupyter notebook. However, the kernel died immediately and the terminal shows the following message:

> A requested component was not found, or was unable to be opened.  This
> means that this component is either not installed or is unable to be
> used on your system (e.g., sometimes this means that shared libraries
> that the component requires are unable to be found/loaded).  Note that
> Open MPI stopped checking at the first component that it did not find.
> Host:      XXXXX.fios-router.home
> Framework: btl
> Component: tcpecho
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> It looks like MPI_INIT failed for some reason; your parallel process is
> likely to abort.  There are many reasons that a parallel process can
> fail during MPI_INIT; some of which are due to configuration or environment
> problems.  This failure appears to be an internal failure; here's some
> additional information (which may only be relevant to an Open MPI
> developer):
> mca_bml_base_open() failed
> --> Returned "Not found" (-13) instead of "Success" (0)
> --------------------------------------------------------------------------
> [XXXXX:82047] *** An error occurred in MPI_Init_thread
> [XXXXX:82047] *** reported by process [246677505,0]
> [XXXXX:82047] *** on a NULL communicator
> [XXXXX:82047] *** Unknown error
> [XXXXX:82047] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> [XXXXX:82047] ***    and potentially your MPI job)
> [I 11:28:13.520 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
> WARNING:root:kernel fdac667e-04be-4c91-9452-bdbd31cbeeff restarted
> 

These are the packages installed in the conda environment I am using:

> # Name                    Version                   Build  Channel
> adaptive                  0.11.1           py37hf985489_3    conda-forge
> appnope                   0.1.2           py37hecd8cb5_1001  
> argon2-cffi               20.1.0           py37haf1e3a3_1  
> async_generator           1.10             py37h28b3542_0  
> atomicwrites              1.4.0                      py_0  
> attrs                     20.3.0             pyhd3eb1b0_0  
> backcall                  0.2.0                      py_0  
> bleach                    3.2.1                      py_0  
> bokeh                     2.2.3                    py37_0  
> brotlipy                  0.7.0           py37h9ed2024_1003  
> ca-certificates           2020.12.5            h033912b_0    conda-forge
> certifi                   2020.12.5        py37hf985489_1    conda-forge
> cffi                      1.14.4           py37h2125817_0  
> chardet                   4.0.0           py37hecd8cb5_1003  
> cloudpickle               1.6.0                      py_0  
> colorcet                  2.0.2                      py_0    pyviz
> cryptography              3.3.1            py37hbcfaee0_0  
> cycler                    0.10.0                   py37_0  
> cython                    0.29.21                  pypi_0    pypi
> dbus                      1.13.18              h18a8e69_0  
> decorator                 4.4.2                      py_0  
> defusedxml                0.6.0                      py_0  
> entrypoints               0.3                      py37_0  
> expat                     2.2.10               hb1e8313_2  
> freetype                  2.10.4               ha233b18_0  
> gettext                   0.19.8.1             hb0f4f8b_2  
> glib                      2.66.1               h9bbe63b_0  
> gmp                       6.1.2                hb37e062_1  
> gmpy2                     2.0.8            py37h6ef4df4_2  
> holoviews                 1.14.1                     py_0    pyviz
> icu                       58.2                 h0a44026_3  
> idna                      2.10                       py_0  
> importlib-metadata        2.0.0                      py_1  
> importlib_metadata        2.0.0                         1  
> iniconfig                 1.1.1                      py_0  
> ipykernel                 5.3.4            py37h5ca1d4c_0  
> ipyparallel               6.3.0                    py37_0  
> ipython                   7.19.0           py37h01d92e1_0  
> ipython_genutils          0.2.0              pyhd3eb1b0_1  
> ipywidgets                7.6.1              pyhd3eb1b0_0  
> jedi                      0.18.0           py37hf985489_1    conda-forge
> jinja2                    2.11.2                     py_0  
> jpeg                      9b                   he5867d9_2  
> jsonschema                3.2.0                      py_2  
> jupyter                   1.0.0                    py37_7  
> jupyter_client            6.1.7                      py_0  
> jupyter_console           6.2.0                      py_0  
> jupyter_core              4.7.0            py37hecd8cb5_0  
> jupyterlab_pygments       0.1.2                      py_0  
> jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
> kiwisolver                1.3.0            py37h23ab428_0  
> kwant                     1.4.2            py37hc44a957_3    conda-forge
> kwantspectrum             0.1.0                      py_0    conda-forge
> lcms2                     2.11                 h92f6f08_0  
> libblas                   3.9.0                7_openblas    conda-forge
> libcblas                  3.9.0                7_openblas    conda-forge
> libcxx                    11.0.0               h4c3b8ed_1    conda-forge
> libedit                   3.1.20191231         h1de35cc_1  
> libffi                    3.3                  hb1e8313_2  
> libgfortran               4.0.0               h1a10cd1_15    conda-forge
> libgfortran4              7.5.0               h1a10cd1_15    conda-forge
> libiconv                  1.16                 h1de35cc_0  
> liblapack                 3.9.0                7_openblas    conda-forge
> libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
> libpng                    1.6.37               ha441bb4_0  
> libsodium                 1.0.18               h1de35cc_0  
> libtiff                   4.1.0                hcb84e12_1  
> llvm-openmp               11.0.0               h73239a0_1    conda-forge
> loky                      2.9.0              pyh9f0ad1d_0    conda-forge
> lz4-c                     1.9.2                h79c402e_3  
> markdown                  3.3.3            py37hecd8cb5_0  
> markupsafe                1.1.1            py37h1de35cc_0  
> matplotlib                3.3.2                hecd8cb5_0  
> matplotlib-base           3.3.2            py37h181983e_0  
> metis                     5.1.0                         0    menpo
> mistune                   0.8.4            py37h1de35cc_0  
> more-itertools            8.6.0              pyhd3eb1b0_0  
> mpc                       1.1.0                h6ef4df4_1  
> mpfr                      4.0.2                h9066e36_1  
> mpi                       1.0                     openmpi  
> mpi4py                    3.0.3            py37h27a7d74_0  
> mpmath                    1.1.0                    py37_0  
> mumps-include             5.2.1               h694c41f_10    conda-forge
> mumps-seq                 5.2.1               h0fefb41_10    conda-forge
> nbclient                  0.5.1                      py_0  
> nbconvert                 6.0.7                    py37_0  
> nbformat                  5.0.8                      py_0  
> ncurses                   6.2                  h0a44026_1  
> nest-asyncio              1.4.3              pyhd3eb1b0_0  
> notebook                  6.1.6            py37hecd8cb5_0  
> numpy                     1.19.5           py37hec87de9_0    conda-forge
> olefile                   0.46                     py37_0  
> openmpi                   4.0.5                h809c96e_4    conda-forge
> openssl                   1.1.1i               h35c211d_0    conda-forge
> packaging                 20.8               pyhd3eb1b0_0  
> pandas                    1.2.0            py37hb2f4e1b_0  
> pandoc                    2.11                 h0dc7051_0  
> pandocfilters             1.4.3            py37hecd8cb5_1  
> panel                     0.10.2                     py_0    pyviz
> param                     1.10.1                     py_0    pyviz
> parso                     0.8.1              pyhd3eb1b0_0  
> pcre                      8.44                 hb1e8313_0  
> pexpect                   4.8.0              pyhd3eb1b0_3  
> pickleshare               0.7.5           pyhd3eb1b0_1003  
> pillow                    8.1.0            py37h5270095_0  
> pip                       20.3.3           py37hecd8cb5_0  
> plotly                    4.14.3                   pypi_0    pypi
> pluggy                    0.13.1                   py37_0  
> prometheus_client         0.9.0              pyhd3eb1b0_0  
> prompt-toolkit            3.0.8                      py_0  
> prompt_toolkit            3.0.8                         0  
> psutil                    5.7.2            py37haf1e3a3_0  
> ptyprocess                0.7.0              pyhd3eb1b0_2  
> py                        1.10.0             pyhd3eb1b0_0  
> pycparser                 2.20                       py_2  
> pyct                      0.4.8                      py_0    pyviz
> pyct-core                 0.4.8                      py_0    pyviz
> pygments                  2.7.3              pyhd3eb1b0_0  
> pyopenssl                 20.0.1             pyhd3eb1b0_1  
> pyparsing                 2.4.7                      py_0  
> pyqt                      5.9.2            py37h655552a_2  
> pyrsistent                0.17.3           py37haf1e3a3_0  
> pysocks                   1.7.1            py37hecd8cb5_0  
> pytest                    6.2.1            py37hecd8cb5_0  
> python                    3.7.9                h26836e1_0  
> python-dateutil           2.8.1                      py_0  
> python_abi                3.7                     1_cp37m    conda-forge
> pytz                      2020.5             pyhd3eb1b0_0  
> pyviz_comms               2.0.1                      py_0    pyviz
> pyyaml                    5.3.1            py37haf1e3a3_1  
> pyzmq                     20.0.0           py37h23ab428_1  
> qsymm                     1.3.0              pyhd8ed1ab_0    conda-forge
> qt                        5.9.7                h468cd18_1  
> qtconsole                 4.7.7                      py_0  
> qtpy                      1.9.0                      py_0  
> readline                  8.0                  h1de35cc_0  
> requests                  2.25.1             pyhd3eb1b0_0  
> retrying                  1.3.3                    pypi_0    pypi
> scipy                     1.5.3            py37h04d6967_0    conda-forge
> scotch                    6.0.9                h57311db_1    conda-forge
> send2trash                1.5.0              pyhd3eb1b0_1  
> setuptools                51.0.0           py37hecd8cb5_2  
> sip                       4.19.8           py37h0a44026_0  
> six                       1.15.0           py37hecd8cb5_0  
> sortedcollections         1.2.3              pyhd3eb1b0_0  
> sortedcontainers          2.3.0              pyhd3eb1b0_0  
> sqlite                    3.33.0               hffcf06c_0  
> sympy                     1.7.1            py37hecd8cb5_0  
> terminado                 0.9.2            py37hecd8cb5_0  
> testpath                  0.4.4                      py_0  
> tinyarray                 1.2.3            py37h6d0141a_0    conda-forge
> tk                        8.6.10               hb0a8c7a_0  
> tkwant                    1.0.1            py37ha805f5d_0    conda-forge
> toml                      0.10.1                     py_0  
> tornado                   6.1              py37h9ed2024_0  
> tqdm                      4.55.1             pyhd3eb1b0_0  
> traitlets                 5.0.5                      py_0  
> typing_extensions         3.7.4.3                    py_0  
> urllib3                   1.26.2             pyhd3eb1b0_0  
> wcwidth                   0.2.5                      py_0  
> webencodings              0.5.1                    py37_1  
> wheel                     0.36.2             pyhd3eb1b0_0  
> widgetsnbextension        3.5.1                    py37_0  
> xz                        5.2.5                h1de35cc_0  
> yaml                      0.2.5                haf1e3a3_0  
> zeromq                    4.3.3                hb1e8313_3  
> zipp                      3.4.0              pyhd3eb1b0_0  
> zlib                      1.2.11               h1de35cc_3  
> zstd                      1.4.5                h41d2c2f_0  
> 

My system is Python 3.7.9, macOS Catalina 10.15.7, MacBook Pro mid 2012, 16GB memory and 2.9GHz Dual-Core Intel Core i7. I tried to run it on python in the Terminal and it shows the same message. It seems to be the Open MPI problem.

Sorry I am not very good at formating for the post.

Does anyone know how to fix it?

Thank you very much!

**Comment by akhmerov** [comment] 2021-01-14 17:35
@basnijholt I think you're running adaptive on a mac without problems. Any ideas?

**Comment by basnijholt** [comment] 2021-02-19 13:56
This doesn't seem to be related to Adaptive but rather a dependency of Adaptive that has issues.

My guess is that mpi4py is the cause. Probably removing that package (if you don't use it) will solve the issue.

**Comment by basnijholt** [comment] 2021-04-06 09:05
I am going ahead and close this because I am relatively sure this is unrelated to Adaptive.

Let me know if I should reopen it.

**Closed by basnijholt** 2021-04-06 09:05 UTC
